created new base setup and included other setup scripts into it; removing setup script not using in future installer

diff --git a/scripts/iod-setup-sdk b/scripts/iod-setup-sdk
--- a/scripts/iod-setup-sdk
+++ b/scripts/iod-setup-sdk
@@ -4,7 +4,6 @@
 # iOSOpenDev -- iOS Open Development (http://www.iOSOpenDev.com)
 # Copyright (C) 2012 Spencer W.S. James <dev@iosopendev.com>
 # --------------------------------------------------------------
-
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation; either version 2 of the License, or
@@ -16,16 +15,20 @@
 # You should have received a copy of the GNU General Public License along
 # with this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-
+# --------------------------------------------------------------
 # iOSOpenDev is an independent project and has not been authorized, sponsored, or otherwise approved by Apple Inc.
 # IOS is a registered trademark of Cisco.
 # Xcode is a registered trademark of Apple Inc.
+# --------------------------------------------------------------
 
 export setCmd="set -eo pipefail"
 $setCmd
 
+# script #
+
 export scriptName="${0##*/}"
-export scriptVer="1.0.1"
+export scriptVer="1.0.2"
+
 export iOSOpenDevPath="/opt/iOSOpenDev"
 
 export backupFileExt=".iOSOpenDev"
@@ -36,7 +39,16 @@ touch "$tempDirsFile"
 
 unset LANG
 
-function cleanup() # no args
+# panic and cleanup #
+
+function panic()
+{
+	local exitCode=$1
+	set +e
+	[[ "$2" == "" ]] || echo "$2" >&2
+	exit $exitCode
+}
+function cleanup()
 {
 	local exitCode=$?
 	set +e
@@ -49,18 +61,7 @@ function cleanup() # no args
 export signals="0 1 2 3 15"
 trap cleanup $signals
 
-function panic() # args: exitCode, message
-{
-	local exitCode=$1
-	set +e
-	
-	[[ "$2" == "" ]] || \
-		echo "$2" >&2
-
-	exit $exitCode
-}
-
-# === functions === #
+# functions #
 
 function removeTempData() # no args
 {
@@ -409,7 +410,7 @@ function requireArgValue()
 
 while [[ "$1" != "" ]]; do case "$1" in
 	-h|--help)
-		echo "iOSOpenDev -- setup SDK for \"open\" development
+		echo "iOSOpenDev: $scriptName v$scriptVer -- setup iOS SDK
 Usage:
     $scriptName [-sdk <sdk>]
 
@@ -430,10 +431,11 @@ Argument:
 	;;
 esac; done
 
-# start #
+# begin script #
 
 export platformName=`getPlatformName "$sdk"`
 export sdkVersion=`getSdkProperty "$sdk" "SDKVersion"`
+
 echo "Setting up $platformName $sdkVersion SDK..."
 
 echo "Modifying SDK settings..."
@@ -445,6 +447,6 @@ addXcodeSpecs "$sdk" "$platformName"
 echo "Creating symlinks in platform bin..."
 addSymlinksToPathAvailableDuringBuilds "$sdk"
 
-# finished #
+# done #
 
 exit 0
